### ISSUE TITLE
Add a posibility to load own template instead of adding an image?

### ISSUE THREAD

**Issue by Eldenroot** [SvePu/ThreadStarter#5]
I would like to use my own template for this (created by this plugin) and use some CSS classes etc. Is that possible please?

**Comment by SvePu** [comment]
I'll take a look 😉

**Comment by SvePu** [comment]
48168ca8f6d42304aa1479698df3c34802ec1bc4

**Comment by Eldenroot** [comment]
Cool, will try soon :)

**Comment by Eldenroot** [comment]
Thank you

**Comment by Eldenroot** [comment]
@SvePu - I dont know, not working... nothing is displayed in postbit... var is here, but no output

![image](https://user-images.githubusercontent.com/778890/203150898-1116764e-f451-4a05-ab93-bed00ffbccfa.png)

**Comment by Eldenroot** [comment]
OK, now it works... it needed some time :)

**Comment by Eldenroot** [comment]
OK, so for the first post it is not working, I think it should display it here... or not? Thats why I was confused :)

**Comment by SvePu** [comment]
No, the mark only will show on following posts of thread starter. I think it isn't necessary to show it on first thread post, because it's the first and only one. 😉
